//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_apply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article_apply()
        {
            this.article = new HashSet<article>();
        }
    
        public int id { get; set; }
        public int apply_user_id { get; set; }
        public string apply_user_name { get; set; }
        public System.DateTime apply_dt { get; set; }
        public MH.Rescue.BIZ.ArticleApplyStatusType apply_status { get; set; }
        public Nullable<System.DateTime> admission_dt { get; set; }
        public string rejected_reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article> article { get; set; }
        public virtual user_account user_account { get; set; }
    }
}
