//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_listview
    {
        public int apply_user_id { get; set; }
        public System.DateTime apply_dt { get; set; }
        public int apply_status { get; set; }
        public Nullable<System.DateTime> admission_dt { get; set; }
        public string rejected_reason { get; set; }
        public string apply_user_name { get; set; }
        public int article_id { get; set; }
        public string title { get; set; }
        public int type { get; set; }
        public string keyword { get; set; }
        public string summary { get; set; }
        public string author_name { get; set; }
        public string author_org { get; set; }
        public string author_dept { get; set; }
        public string file_type { get; set; }
        public string file_path { get; set; }
        public Nullable<int> file_size { get; set; }
        public int download_count { get; set; }
        public int like_count { get; set; }
        public Nullable<int> apply_id { get; set; }
        public System.DateTime publish_dt { get; set; }
    }
}
