//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consultation()
        {
            this.consultation_conclusion = new HashSet<consultation_conclusion>();
            this.consultation_resource = new HashSet<consultation_resource>();
        }
    
        public int id { get; set; }
        public int patient_id { get; set; }
        public string chief_complaint { get; set; }
        public string present_illness_history { get; set; }
        public string primary_diagnosis { get; set; }
        public string treatment_plan { get; set; }
        public string description { get; set; }
        public System.DateTime created_dt { get; set; }
        public System.DateTime modified_dt { get; set; }
        public int owner_id { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> admission_dt { get; set; }
        public string rejected_reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultation_conclusion> consultation_conclusion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultation_resource> consultation_resource { get; set; }
        public virtual emr_patient emr_patient { get; set; }
    }
}
