//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class decision_support
    {
        public int id { get; set; }
        public string disease_name { get; set; }
        public string disease_position { get; set; }
        public string symptoms { get; set; }
        public string signs { get; set; }
        public string image_indication { get; set; }
        public string lab_indication { get; set; }
        public string key_point_diagnosis { get; set; }
        public string emergency_treatment { get; set; }
    }
}
