//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class emr_index
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emr_index()
        {
            this.consultation_resource = new HashSet<consultation_resource>();
            this.emr_image = new HashSet<emr_image>();
        }
    
        public int patient_id { get; set; }
        public int type_id { get; set; }
        public string type_name { get; set; }
        public int img_count { get; set; }
        public string contents { get; set; }
        public string contents_t { get; set; }
        public string hospital { get; set; }
        public string hospital_t { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public Nullable<System.DateTime> modified_dt { get; set; }
        public int id { get; set; }
    
        public virtual emr_type emr_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultation_resource> consultation_resource { get; set; }
        public virtual emr_patient emr_patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emr_image> emr_image { get; set; }
    }
}
