//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public Nullable<int> message_sender_id { get; set; }
        public int message_receiver_id { get; set; }
        public string message_sender_name { get; set; }
        public string message_receiver_name { get; set; }
        public System.DateTime sent_dt { get; set; }
        public string message_content { get; set; }
        public bool is_read { get; set; }
        public bool is_deleted { get; set; }
        public string title { get; set; }
    
        public virtual user_account send_user { get; set; }
        public virtual user_account receive_user { get; set; }
    }
}
