//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_image
    {
        public int image_id { get; set; }
        public string description { get; set; }
        public int news_id { get; set; }
        public int id { get; set; }
        public int sorting_no { get; set; }
    
        public virtual news news { get; set; }
        public virtual cmn_image cmn_image { get; set; }
    }
}
