//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientcase_conclusion
    {
        public int id { get; set; }
        public int case_id { get; set; }
        public int user_id { get; set; }
        public string conclusion { get; set; }
        public System.DateTime created_dt { get; set; }
    
        public virtual patientcase patientcase { get; set; }
        public virtual user_account user_account { get; set; }
    }
}
