//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientcase_imageview
    {
        public int case_id { get; set; }
        public int image_id { get; set; }
        public string description { get; set; }
        public int sorting_no { get; set; }
        public int case_image_id { get; set; }
        public string path { get; set; }
        public string thumbnail { get; set; }
        public string oss_url { get; set; }
        public string oss_thumbnail_url { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
