//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RescueEntities : DbContext
    {
        public RescueEntities()
            : base("name=RescueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<article_apply> article_apply { get; set; }
        public virtual DbSet<article_comments> article_comments { get; set; }
        public virtual DbSet<article_like> article_like { get; set; }
        public virtual DbSet<cmn_image> cmn_image { get; set; }
        public virtual DbSet<consultation> consultation { get; set; }
        public virtual DbSet<consultation_conclusion> consultation_conclusion { get; set; }
        public virtual DbSet<consultation_resource> consultation_resource { get; set; }
        public virtual DbSet<decision_support> decision_support { get; set; }
        public virtual DbSet<dic_common> dic_common { get; set; }
        public virtual DbSet<dic_common_item> dic_common_item { get; set; }
        public virtual DbSet<dic_county> dic_county { get; set; }
        public virtual DbSet<dic_hospital> dic_hospital { get; set; }
        public virtual DbSet<dic_live_channel> dic_live_channel { get; set; }
        public virtual DbSet<dic_province> dic_province { get; set; }
        public virtual DbSet<emr_image> emr_image { get; set; }
        public virtual DbSet<emr_index> emr_index { get; set; }
        public virtual DbSet<emr_patient> emr_patient { get; set; }
        public virtual DbSet<emr_type> emr_type { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<news_comments> news_comments { get; set; }
        public virtual DbSet<news_image> news_image { get; set; }
        public virtual DbSet<sms_message_queue> sms_message_queue { get; set; }
        public virtual DbSet<teaching_apply> teaching_apply { get; set; }
        public virtual DbSet<teaching_category> teaching_category { get; set; }
        public virtual DbSet<teaching_comments> teaching_comments { get; set; }
        public virtual DbSet<teaching_like> teaching_like { get; set; }
        public virtual DbSet<teaching_liv> teaching_liv { get; set; }
        public virtual DbSet<teaching_vod> teaching_vod { get; set; }
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<user_collect_record> user_collect_record { get; set; }
        public virtual DbSet<user_download_record> user_download_record { get; set; }
        public virtual DbSet<user_im> user_im { get; set; }
        public virtual DbSet<user_share_record> user_share_record { get; set; }
        public virtual DbSet<patientcase> patientcase { get; set; }
        public virtual DbSet<patientcase_conclusion> patientcase_conclusion { get; set; }
        public virtual DbSet<patientcase_image> patientcase_image { get; set; }
        public virtual DbSet<article_listview> article_listview { get; set; }
        public virtual DbSet<patientcase_imageview> patientcase_imageview { get; set; }
        public virtual DbSet<news_imageview> news_imageview { get; set; }
    }
}
