//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class teaching_vod
    {
        public int id { get; set; }
        public Nullable<int> specialist_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> material_id { get; set; }
        public string video_code { get; set; }
        public System.DateTime created_dt { get; set; }
        public int creator_id { get; set; }
        public int view_count { get; set; }
        public int like_count { get; set; }
        public Nullable<int> image_id { get; set; }
        public VodVideoType video_type { get; set; }
        public string pull_url { get; set; }
        public string teacher_name { get; set; }
        public string teacher_title { get; set; }
        public string teacher_dept { get; set; }
        public string teacher_org { get; set; }
    
        public virtual teaching_category teaching_category { get; set; }
        public virtual cmn_image cmn_image { get; set; }
        public virtual user_account specialist_user { get; set; }
        public virtual user_account create_user { get; set; }
    }
}
