//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_download_record
    {
        public int id { get; set; }
        public Nullable<ContentType> content_type { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<System.DateTime> download_dt { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
