//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        public string account { get; set; }
        public string password { get; set; }
        public MH.Rescue.BIZ.UserRoleType role { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobile_number { get; set; }
        public System.DateTime created_dt { get; set; }
        public Nullable<System.DateTime> modified_dt { get; set; }
        public string hospital_name { get; set; }
        public string id_number { get; set; }
        public string department_name { get; set; }
        public Nullable<MH.Rescue.BIZ.GenderType> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string avatar { get; set; }
        public int id { get; set; }
        public UserStatusType status { get; set; }
    }
}
