//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MH.Rescue.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_im
    {
        public int user_id { get; set; }
        public string server_id { get; set; }
        public string token { get; set; }
        public string account { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public Nullable<System.DateTime> modified_dt { get; set; }
        public int id { get; set; }
    }
}
